apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"angie","namespace":"f2g"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"angie"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"angie"}},"spec":{"containers":[{"env":[{"name":"ENVIRONMENT","valueFrom":{"configMapKeyRef":{"key":"environment","name":"env-config"}}}],"image":"$GCR_DOCKER_REPO/angie:latest","livenessProbe":{"exec":{"command":["healthcheck"]},"initialDelaySeconds":3,"periodSeconds":5,"timeoutSeconds":3},"name":"angie","ports":[{"containerPort":80,"protocol":"TCP"}],"readinessProbe":{"exec":{"command":["healthcheck"]},"initialDelaySeconds":60,"periodSeconds":3,"timeoutSeconds":3},"volumeMounts":[{"mountPath":"/var/log","name":"logs"}]}],"volumes":[{"hostPath":{"path":"/LOGS/angie"},"name":"logs"}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: angie
  name: angie
  selfLink: /apis/extensions/v1beta1/namespaces/f2g/deployments/angie
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: angie
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: angie
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              key: environment
              name: env-config
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws-s3-keys
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws-s3-keys
        image: $GCR_DOCKER_REPO/angie:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - healthcheck
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        name: angie
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - healthcheck
        resources:
          requests:
            memory: 200Mi
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 3
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
